FROM siconos/siconos-ubuntu:18.04
USER root
RUN  apt update && apt install -y -qq \
        liboce-foundation-dev \
        liboce-modeling-dev \
        liboce-ocaf-dev \
        liboce-visualization-dev
RUN mkdir -p /builds/nonsmooth/siconos-tutorials
ENV CI_PROJECT_DIR /builds/nonsmooth/siconos-tutorials
RUN git clone https://gricad-gitlab.univ-grenoble-alpes.fr/nonsmooth/siconos-tutorials.git
# RUN sh siconos-tutorials/ci/install_oce.sh
RUN apt clean
RUN useradd -ms /bin/bash siconos-user
RUN mkdir -p /home/siconos-user
RUN mv siconos-tutorials  /home/siconos-user
RUN chown -R siconos-user /home/siconos-user
USER siconos-user
WORKDIR /home/siconos-user
