# --- set required siconos version to run examples ---
set(MAJOR_VERSION 4)
set(MINOR_VERSION 5)
set(PATCH_VERSION 0)
set(SICONOS_REQUIRED_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}")

SET(SICONOS_MIN_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}")
