FROM andrewosh/binder-base

USER root

RUN \
  apt-get update -y && apt-get install -y --force-yes \
  git-core \
  wget \
  make \
  cmake \
  libboost-dev \
  libgmp-dev \
  swig \
  libcppunit-dev \
  gcc \
  gfortran \
  g++ \
  libblas-dev \
  liblapack-dev \
  libatlas-base-dev \
  libatlas-dev \
  lp-solve \
  liblpsolve55-dev \
  python \
  python-dev \
  python-lxml \
  python-pytest \
  python-scipy \
  python-matplotlib \
  wget \
  bash \
  libbullet-dev \
  python-h5py \
  libgl1-mesa-glx \
  libglu1-mesa \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libglapi-mesa \
  libfreetype6-dev \
  doxygen \
  python-sphinx \
  libbullet-dev
RUN mkdir -p /usr/local
RUN conda remove libgfortran && \
    conda install libgcc --force
RUN \
  wget https://github.com/tpaviot/oce/archive/OCE-0.17.2.tar.gz && \
  wget https://github.com/tpaviot/pythonocc-core/archive/0.17.zip && \
  git clone https://github.com/siconos/siconos.git && \
  git clone https://github.com/siconos/siconos-tutorials.git && \
  mkdir build && \
  cd build && \
  mkdir oce-last pythonocc siconos && \
  cd oce-last && \
  cmake ../../oce-OCE-0.17.2 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release && \
  make -j 4 && \
  make install && \
  cd ../pythonocc && \
  cmake ../../pythonocc-core-0.17 -DCMAKE_BUILD_TYPE=Release && \
  make install && \
  cd ../siconos && \
  cmake ../../siconos -DUSER_OPTIONS_FILE=../../siconos-tutorial/conf/siconos_default.cmake&& \
  make -j 4 && \
  make install

